# Generated by Django 5.0 on 2026-05-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_add_commune_coords'),
        ('patients', '0013_customfield_cancercustomvalue'),
    ]

    operations = [
    ]
